server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vcplatform?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true         
    properties:
      hibernate:
        'format_sql: true'  

  mvc:
    cors:
      allowed-origins: http://localhost,http://localhost:80,http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
    web:
      resources:
        static-locations: classpath:/static/
        add-mappings: true

logging:
  level:
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql]': TRACE
    '[root]': INFO
    '[org.springframework.web]': DEBUG

# JWT配置
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000  # 24小時
  refresh-expiration: 604800000  # 7天
